### ISSUE TITLE
Enable MSS access point when USB thethering used

### ISSUE THREAD

**Issue by cyberorg** [RechercheTech/mss#100]
Create update script

**Comment by cyberorg** [comment]
mssupdate https://repo.myscoolserver.com/fixes/ 20200502-usbap

**Comment by cyberorg** [comment]
for accesspoint ID and password
Create /home/mssadmin/.config/accesspoint.conf
AP_SSID=accesspointname
AP_PASS=accesspointpass

Without the config the default SSID is MSS without any password

**Comment by intelliant01** [comment]
Functionality changed. This is no longer relevant. Hence closing this.
