### ISSUE TITLE
Enable internet access for AP clients when available

### ISSUE THREAD

**Issue by cyberorg** [RechercheTech/mss#106]
mssupdate https://repo.myscoolserver.com/fixes/ 20200505-enablenetap

**Comment by intelliant01** [comment]
@cyberorg what are the steps to test this?

**Comment by cyberorg** [comment]
While in hotspot mode connect the device via usb tethering or wired in dynamic. The AP clients should get net access.

**Comment by intelliant01** [comment]
Would be desirable to have this feature "togglable" for child security and distraction free studying. Great if this can be controlled via the ap page. At least it will work initially for small children till we don't secure the ap page itself.

**Comment by cyberorg** [comment]
See https://github.com/RechercheTech/mss/issues/114
