### ISSUE TITLE
Hide sugar user from ldm login screen

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#138]
sugar being a system user needs to be hidden from the login screen.

**Comment by intelliant01** [comment]
1. `usermod -s /sbin/nologin sugar`  

Restarted lightdm. Works but seems to break sugar - `systemctl status sugar`. Hence shell reverted to `/bin/bash` 


2. Adding to `hidden-users` in `/etc/lightdm/user.conf` doesn't seem to work.

Restarted lightdm. Doesn't work.

3. Neither does `/var/lib/AccountsService/users/sugar` with this -
```
[User]
SystemAccount=true
```

System rebooted. Works.

4. Id below 500 may have worked as well. Not needed as of now.

**Comment by intelliant01** [comment]
@cyberorg Review and close if you concur as this being the recommended way.

**Comment by cyberorg** [comment]
Use usersdd -r option when adding sugar user, see gstudio script.

**Comment by intelliant01** [comment]
As of now option 3 applied from [here](https://github.com/RechercheTech/mss/issues/138#issuecomment-645593999) to hide.

**Comment by intelliant01** [comment]
@cyberorg May this be closed as ``useradd -r`` doesn't seem to have been used and option 3 worked?

**Comment by cyberorg** [comment]
Yes, close it
