### ISSUE TITLE
Sugar not working on Pi and MSS

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#139]
Noticed `Waiting for DB... (MongoNetworkError)` in sugarizer.log

**Comment by intelliant01** [comment]
Was reinstalling on Pi using mssupdate sugar-pi as I noticed some differences. Pi hung and now doesn't boot due to kernel panic.

**Comment by cyberorg** [comment]
https://github.com/RechercheTech/mss/pull/141
