### ISSUE TITLE
Option to completely turn off hotspot on Pi 

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#142]
This will be useful when Pi needs to connect to an existing home network and to prevent interference with existing home WiFi. This use case is applicable for intermediate and above technical users.

Need to -
1. Warn that WiFi access shall be completely lost until reconfigured by connecting a "head" (TV / monitor / screen). 
2. Inform to configure dns mapping for myscoolserver.in in their dns server to the IP assigned to Pi.

**Comment by cyberorg** [comment]
let this be done via network manager not remotely, then the user know where to re-enable when required.

**Comment by intelliant01** [comment]
>     1. Warn that WiFi access shall be completely lost until reconfigured by connecting a "head" (TV / monitor / screen).

We are already telling them that they shall be able to re-enable via cockpit itself. Cockpit will be the definite place for all configuration. As we saw today, network manager is not playing well with our customisation, so why even take the user there.

**Comment by intelliant01** [comment]
Actually wlan0 can easily be disabled via cockpit->networking itself. And user will not get any warning. :) 
So they either know what they are doing or head to our FAQ and / or support thereafter.
