### ISSUE TITLE
Python IDLE

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#160]
@cyberorg Need to include idle-python3.6 or later in client image to match instructions in [PMP book 8 pg 130](https://share.wakelet.com/doc/aSAAF-AUpfteRH4RvqaiP)

**Comment by cyberorg** [comment]
Use pip for any python module that is needed only once for demo.

**Comment by intelliant01** [comment]
Added to 18.044 image. Details in https://github.com/RechercheTech/mss/issues/165#issuecomment-793463226.
