### ISSUE TITLE
Unable to select sprites and backgrounds in scratch 3.0

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#166]
Thumbnails of sprites and backgrounds are visible but can't be selected and used.
This is irrespective of being offline or online. 
Same experience on server and clients.
Schools wanting to use it now are reporting this issue.

**Comment by intelliant01** [comment]
This works fine when using Scratch from within Sugar. But Scratch in sugar doesn't allow working with project files.

**Comment by cyberorg** [comment]
apt update
apt install scratch-web

**Comment by cyberorg** [comment]
There is no such package, install chromium and use launcher from mss portal.

If you need a launcher then create one, see the one that comes with scratch-web package for reference.

**Comment by intelliant01** [comment]
Works on RPi client too.
