### ISSUE TITLE
gcompris downloads fail 

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#167]
gcompris needs to download a few sounds and images based on the user's chosen language.
Since MSS is primarily an offline solution, the download fails.
Need a solution to workaround the need to download.
The relevant language supported in Gcompris 1.1 is English.

**Comment by cyberorg** [comment]
Done already, see /etc/skel in pi chroot.

**Comment by intelliant01** [comment]
> Done already, see /etc/skel in pi chroot.

Am aware. Had created this as a reminder stub for myself to check, document, close and reference when users contact us.

**Comment by cyberorg** [comment]
rm -rf /home/*/.config/gcompris* /home/*/.cache/KDE
for i in `ls /home/`; do
cp -r ...
done
