### ISSUE TITLE
Bluetooth auth dialog pops up for every user

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#169]
On RPi, the below dialog pops up for every user just after login and times out after a while -

![IMG_20211007_212042.jpg](https://user-images.githubusercontent.com/2577060/136419808-87116b37-7188-4f4e-a403-7c188ed7b844.jpg)

Seems this is to start bluetooth by asking for super user priviledges. There needs to be a way to get bluetooth working without elevated permissions.

Need to get rid of this. But bluetooth should work.

**Comment by intelliant01** [comment]
Doesn't work.

You may have done something additional if you have it working correctly. I tested with teacher1.

**Comment by intelliant01** [comment]
Added, then had to execute ltsp initrd as it seems the inotifywait logic is not yet taking care of addition to groups.

> Need to get rid of this. But bluetooth should work.

Popup doesn't show anymore but user can't use bluetooth related services now.

Guess will have to revert the changes made to polkit? I don't have a backup. 

![IMG_20211015_122116.jpg](https://user-images.githubusercontent.com/2577060/137444494-ba27a24b-82b0-4dae-a1f9-943c5228b8e6.jpg)

Do note that gid of netdev on pi is different from that on x86.

For new users, got to add to /etc/adduser.conf -
![IMG_20211015_121041.jpg](https://user-images.githubusercontent.com/2577060/137444874-75b88b18-487f-42f6-bcae-b81ece355536.jpg)

For all old users, will have to add via a script or possible via a config?

Pls test the complete solution at your end.

**Comment by cyberorg** [comment]
in the image
apt reinstall blueman

**Comment by intelliant01** [comment]
![IMG_20211015_133913.jpg](https://user-images.githubusercontent.com/2577060/137454360-fd8a0036-a87d-4631-8148-cbfb13c01bb7.jpg)

Not sure what is preventing this....will try again after sometime. Could be servers.

**Comment by intelliant01** [comment]
Reinstall worked after update.

What about the other changes I have mentioned?
