### ISSUE TITLE
KDE Plasma does not work in new ltsp amd64 image

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#171]
Login to KDE Plasma desktop does not work in the new ltsp amd64 image. Reason unknown. Login attempt loops back to the login screen.

The only use case for this as of now is the support for Benq panels via the touch screen drivers which were working fine in Plasma. Not a deal breaker for now but nice to continue supporting it.

**Comment by cyberorg** [comment]
works on the image just synced
