### ISSUE TITLE
RPi not showing correct time in static mode

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#172]
ltsp.conf has `TIMESERVER=server` .
NTP service seems to be running fine on server.
But in static mode RPi doesn't reflect correct time.

**Comment by cyberorg** [comment]
there is no TIMESERVER variable in ltsp, change this file and recreate the image:

/home/mss-images/mssraspi# cat etc/systemd/timesyncd.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See timesyncd.conf(5) for details.

[Time]
NTP=server
#FallbackNTP=ntp.ubuntu.com
#RootDistanceMaxSec=5
#PollIntervalMinSec=32
#PollIntervalMaxSec=2048

**Comment by intelliant01** [comment]
@cyberorg This shall apply to amd64 image as well?

**Comment by cyberorg** [comment]
No, it is 18.04

**Comment by intelliant01** [comment]
Changed time in Client's BIOS and booted via MSS in static mode.
Time was messed up.
Above setting done in image and rebooted. Fixed.
So the above is applicable for 18.04 amd64 image as well.
