### ISSUE TITLE
Integrate wifi  access point

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#18]
_From @cyberorg on February 28, 2017 9:24_

Keeping MSS simple is one of the most important feature, hence we will not be integrating anything that can be done more efficiently by external devices/services. No modifications are needed on MSS to make use of external wifi router's capabilities to serve content>

Any wifi routers https://www.google.com/search?q=buy+wifi+router+india has web based GUI for configuration, are cheap, easy to extend as per number of connections required and easy to maintain.

_Copied from original issue: RechercheTech/mss-doc#18_

**Comment by intelliant01** [comment]
_From @cyberorg on June 15, 2017 8:1_

A very basic wifi access point on hardwares that support AP mode will be set up, this feature is also too complicated to implement on MSS, just not worth all the effort when the same and more is easily achieved using cheap external AP. For more complicated AP with authentication etc. use add-on AP hardware.

**Comment by intelliant01** [comment]
_From @cyberorg on June 22, 2017 12:40_

mssupdate install.server.ip mssap

Will set up very basic wifi accesspoint with no password. For more complex setup see "create_ap --help" and modify /usr/bin/mssap script accordingly.

mssap script provides basic management: stop, enable, disable, unmanage

Network is not manageable by NetworkManager while AP mode is on, so to switch static/dynamic or modify it run "mssap stop"

enable and disable options for service start during boot.

Sometimes "mssap stop" does not release the devices it is managing, to let NetworkManager manage it again run "mssap unmanage"

**Comment by intelliant01** [comment]
_From @cyberorg on June 27, 2017 13:13_

Needs hostapd and haveged installed, which is not available on older MSS.

apt update && apt install hostapd haveged

We also need one updated script

cd /usr/bin/
rm networkvariables.sh
 wget installserverip/mss/networkvariables.sh && chmod +x networkvariables.sh

**Comment by intelliant01** [comment]
> Needs hostapd and haveged installed

> apt update && apt install hostapd haveged

@cyberorg Guess this is only needed on older nuc mss installs.

And thereafter when I do```mssupdate <install_server_ip> mssap``` I am getting this error -

```
$ sudo mssupdate 192.168.2.30 mssap
[sudo] password for mssadmin: 
--2017-06-27 18:45:59--  http://192.168.2.30/mss/mssap
Connecting to 192.168.2.30:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 91
Saving to: ‘mssap’

mssap               100%[===================>]      91  --.-KB/s    in 0s      

2017-06-27 18:45:59 (6.81 MB/s) - ‘mssap’ saved [91/91]

--2017-06-27 18:45:59--  http://192.168.2.30/mss/mssap.tar.xz
Connecting to 192.168.2.30:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14656 (14K) [application/x-xz]
Saving to: ‘mssap.tar.xz’

mssap.tar.xz        100%[===================>]  14.31K  --.-KB/s    in 0s      

2017-06-27 18:45:59 (130 MB/s) - ‘mssap.tar.xz’ saved [14656/14656]

etc/
etc/create_ap.conf
usr/
usr/bin/
usr/bin/create_ap
usr/bin/mssap
usr/lib/
usr/lib/systemd/
usr/lib/systemd/system/
usr/lib/systemd/system/mssap.service
usr/share/
usr/share/bash-completion/
usr/share/bash-completion/completions/
usr/share/bash-completion/completions/create_ap
grep: wlp2s0: No such file or directory
something went wrong

```

**Comment by intelliant01** [comment]
@cyberorg Found the reason of the above error. The wifi adapter should not be connected in client mode when attempting the install.

**Comment by intelliant01** [comment]
@cyberorg Let's not enable it by default upon installation as 1. user documentation does not outline the process of disabling it, hence rendering NM unusable, 2. It is not going to be a standard requirement. 
Have done the requisite change on the install server.

Once documented, may enable it by default.

**Comment by cyberorg** [comment]
mssupdate install.server.ip mssap is needed to install and enable it, which is not done in default installation. Run "mssap disable" if not needed after it is installed.

**Comment by intelliant01** [comment]
@cyberorg Will keep this open until documented.

**Comment by intelliant01** [comment]
From https://github.com/RechercheTech/mss/issues/33#issuecomment-351012769 : 

>Add the following line to /usr/bin/mssipchange before systemctl restart dnsmasq
>echo "address=/#/$SERVER_IP" >> /etc/dnsmasq.d/ltsp-server-dnsmasq.conf
>
>man dnsmasq for "-A, --address=//[domain/][]" option.
>
>With this option the access point will not be used as internet access point but will just serve content from mss.

Such small tweaks beg an easy user interface for layman usage.

**Comment by intelliant01** [comment]
> echo "address=/#/$SERVER_IP" >> /etc/dnsmasq.d/ltsp-server-dnsmasq.conf

Good to know but not very useful in our context.
