### ISSUE TITLE
Install zabbix monitoring server to track MSS usage

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#29]
_From @intelliant01 on May 25, 2017 18:53_

Would be best to install a Zabbix server on an AWS EC2 instance. If feasible must try to install on the same server as which hosts the MSS website.

Some links which may be explored further and followed - 

* http://www.endlick.com/install-zabbix-on-an-aws-instance-with-amazon-linux/
* https://www.skyarch.net/blog/?p=8557&lang=en
* https://aws.amazon.com/marketplace/pp/B01JZ0AJW4

_Copied from original issue: RechercheTech/mss-doc#41_

**Comment by cyberorg** [comment]
Ref: sqlite corruption: https://support.zabbix.com/browse/ZBX-6036

Add the following to /etc/rc.local to start zabbix proxy after deleting bad db, it does not address the reason or fix for corruption.

/bin/echo "SELECT count(*) FROM proxy_history;" | /usr/bin/sqlite3 /var/lib/zabbix/zabbix_proxy.db &>/dev/null || /bin/rm /var/lib/zabbix/zabbix_proxy.db &>/dev/null || /bin/true

**Comment by intelliant01** [comment]
Have added this  as the zabbix_proxy.db-journal file also needs to be deleted.

```/bin/echo "SELECT count(*) FROM proxy_history;" | /usr/bin/sqlite3 /var/lib/zabbix/zabbix_proxy.db &>/dev/null || /bin/rm /var/lib/zabbix/zabbix_proxy.db* &>/dev/null || /bin/true```
