### ISSUE TITLE
Launch captive portal as wifi client device connects to MSS AP

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#33]
In continuation of #18 , we need to try to launch the offlineweb content page as a "captive portal". This is needed because we mostly intend to run the MSS headless. Hence it will be difficult as well as inconvenient to check the IP of MSS when it is in dynamic mode. Also if in static mode, it will be a better user experience if the portal is launched automatically instead of having to manually type in the IP in a mobile browser.

**Comment by intelliant01** [comment]
From Jigish Gohil : 

https://www.howtoforge.com/tutorial/how-to-install-a-wireless-hotspot-with-captive-page-in-linux-using-coovachilli/ 

probably easily done on cheap wifi routers

http://www.pihomeserver.fr/en/2014/05/23/raspberry-pi-home-server-creer-hot-spot-wifi-portail-captif-22/
this will work too

**Comment by intelliant01** [comment]
@cyberorg Both the above methods are made complicated with authentication thrown in. We don't need authentication. Hence will have to improvise on either of these or make something of our own.

**Comment by cyberorg** [comment]
Add the following line to /usr/bin/mssipchange before systemctl restart dnsmasq
`echo "address=/#/$SERVER_IP" >> /etc/dnsmasq.d/ltsp-server-dnsmasq.conf`

man dnsmasq for "-A, --address=/<domain>/[domain/][<ipaddr>]" option.

With this option the access point will not be used as internet access point but will just serve content from mss.
