### ISSUE TITLE
MSS wifi client connection disrupts booting over ethernet

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#37]
When MSS wifi port is connected to a network, the network booting over ethernet is disrupted.

**Comment by intelliant01** [comment]
@cyberorg The fix applied in the latest release fixes the above problem and it has been tested as follows -
ethernet in static mode + wifi adapter connected to network other than that of ethernet
ethernet in dynamic mode + wifi adapter connected to network other than that of ethernet

How can this fix be rolled out to MSS units already deployed prior to this fix?

**Comment by cyberorg** [comment]
mssupdate serverip fixwifi
