### ISSUE TITLE
Users are unable to change their password in fat-client mode

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#40]
Students are unable to change their passwords on their own when booting into fat-client mode.

After hitting OK if the password is unacceptable due to rules then it reverts but if the password is a qualifying one there is no revert and it continues waiting or even if it returns with an affirmative, the password remains unchanged. Have also tried logging off, rebooting and relogin after a password change attempt.

Password change does not work through terminal also, it appears to do so but it doesn't.

Users being able to easily change their own password is critical to the workflow and ease of use of the MSS.

How can we make that happen even if we have to make it happen via the terminal? One method is by user doing a ssh to the server. Need something simpler.

**Comment by intelliant01** [comment]
```ssh server passwd``` works.

May be a wrapper for passwd in the fat-client image will be better and/or a UI wrapper can also be worked upon for a future enhancement.

**Comment by cyberorg** [comment]
Alt+F2 -> ltsp-remoteapps users-admin
Alt+F2 -> ltsp-remoteapps xterm -> passwd
