### ISSUE TITLE
MSS mandates BIOS to be set with GMT time 

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#41]
MSS mandates BIOS to be set with GMT time which conflicts with the default windows behaviour which directly reads and writes bios / hwclock time. It is not possible to enforce a behaviour on Windows systems where both mss and windows are being used to teach.

**Comment by cyberorg** [comment]
mssupdate repo.myscoolserver.com/fixes 20170818-ntp

**Comment by geets04** [comment]
@cyberorg Does MSS need a mandatory restart after applying this fix?

**Comment by cyberorg** [comment]
Don't know, restart is best policy if unsure.

**Comment by intelliant01** [comment]
@geets04 Restart is mandatory. Verified.
@cyberorg Pls try to include completely verified steps as many a times we have very little scope for trials while we try to rollout updates over remote sessions and between classes.
