### ISSUE TITLE
User creation anomaly

### ISSUE THREAD

**Issue by geets04** [RechercheTech/mss#42]
In Fat-client mode, with mssadmin login, users are not created with -
```Alt+F2 -> ltsp-remoteapps users-admin ```

But change of password is working.

To create users, I had to use legacy client mode as mssadmin.

Is this the expected behaviour w.r.t. user creation ?

**Comment by cyberorg** [comment]
Only root or sudo user(mssadmin) can create users.

**Comment by geets04** [comment]
As i have written above, i am trying with mssadmin

**Comment by intelliant01** [comment]
Yes ltsp-remoteapps does not effect sudo rights of a user, hence not even of mssadmin.

Worth documenting.

**Comment by cyberorg** [comment]
Right, missed "with mssadmin login" so for user management, log in using thin-client mode, rdesktop(Remote Desktop from windows) or log in directly on the server.

**Comment by cyberorg** [comment]
Right, missed "with mssadmin login" so for user management, log in using thin-client mode, rdesktop(Remote Desktop from windows) or log in directly on the server.
