### ISSUE TITLE
Some clients do not boot up completely in Legacy mode

### ISSUE THREAD

**Issue by cyberorg** [RechercheTech/mss#44]
Legacy and Fatclient both use same image to boot, only difference between the two is this parameter. Add the following to lts.conf for those client to boot in default depth same as fatclient.

       X_SMART_COLOR_DEPTH
           boolean, default True

           If set, thin clients no longer default to 16 bit colour depth but use the X server default instead.

**Comment by intelliant01** [comment]
Fix deployed in lts.conf under custom sections for both machines -

[mac id]
X_SMART_COLOR_DEPTH=False

It works.

**Comment by intelliant01** [comment]
@cyberorg We are noticing that a lot of new machines are needing this including the Intel NUC when used as client.

**Comment by cyberorg** [comment]
Have made  X_SMART_COLOR_DEPTH=False default now.
