### ISSUE TITLE
GCompris activities become unresponsive quite a few times and need to be Force Quit

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#47]
Experienced today on Atom based clients that certain activities did become completely unresponsive and had to be quit using these steps 
1. Show desktop - ctrl+alt+d
2. right click on Gcompris in task bar and Close
3. Select Force Quit in the dialog that pops up after around 15 seconds

Some of the activities which were causing this problem were traversing the maze.
It could be due to low end client spec which need to be validated. This needs to be validated further before escalation.

**Comment by cyberorg** [comment]
also test new gcompris on 1804 on the same clients.

**Comment by intelliant01** [comment]
Shall reopen if we have such incidents reported again.
