### ISSUE TITLE
Kolibri

### ISSUE THREAD

**Issue by cyberorg** [RechercheTech/mss#51]
On fresh installed MSS:

mssupdate $INSTSERVER kolibri

On older MSS:
apt update
apt install python-pip
wget http://$INSTSERVER/mss/kolibri-0.6.1.dev020171121234502-git
pip install /path/to/kolibri-0.6.1.dev020171121234502-git
mssupdate $INSTSERVER kolibri

Add the following to /usr/bin/mssipchange
sed -i -e s"@http://.*:@http://$SERVER_IP:@g" /var/www/html/mss/index.html 2>/dev/null || true

Copy ~/.kolibri from server on which it is set up as needed to installserver /home/mss/content/kolibrif/home/mssadmin/.kolibri and create the tar for deployment.

Ref: https://www.gitbook.com/book/learningequality/kolibri-content-workshop-user-guide/details 
http://kolibri.readthedocs.io/en/develop/manage.html#manage-content

**Comment by intelliant01** [comment]
Works as expected.

**Comment by intelliant01** [comment]
@cyberorg Update to 0.7.x ASAP as the feature to selectively export and import individual channels is much desired.

**Comment by cyberorg** [comment]
Manually update it on MSS that need it and test it out thoroughly, will include in image only if fully functional.

**Comment by intelliant01** [comment]
Should we download the deb and do this -
```sudo dpkg -i kolibri-installer-filename.deb```
or are there any custom steps?

**Comment by cyberorg** [comment]
download .pex and rename/copy it as /usr/local/bin/kolibri

**Comment by Harvindersingh0114** [comment]
@cyberorg whatever was working in 0.6 is working in 0.7 as well as some new features are there which are also working. Tested with the .pex as advised.

**Comment by cyberorg** [comment]
Try export and import of khanacademy

**Comment by Harvindersingh0114** [comment]
@cyberorg Sir we have tried to export Khan academy(hi) , Be Strong: Internet safety resources and PhET Interactive Simulations (en) and we don't have enough storage device to export Khan academy(en).
PS: We have tried to import the exported content as listed above on Android device but it could not import from external disk or local drive, i have mentioned this at 
https://community.learningequality.org/t/kolibri-in-android-os/441

**Comment by cyberorg** [comment]
OK, updated
