### ISSUE TITLE
gstudio

### ISSUE THREAD

**Issue by cyberorg** [RechercheTech/mss#52]
On the MSS after the changelog entry(new install that has the following /changelog entry:
---------------------------
- add gstudio deps

mssupdate installserverip gstudio

http://localhost:8800/
http://localhost:8800/admin (administrator:changeit, user creation from there does not work though)

grep docker /home/docker/code/gstudio/gnowsys-ndf/gnowsys_ndf/local_settings.py

Put all the data in paths mentioned in local_settings, check with gstudio team on how to export and import data from one installation to another and import in mss as per their instructions.

For older mss installs:
-----------------------
-- Install required packages:
-----------------------

sudo apt-get install python-setuptools git build-essential python-dev rcs python-virtualenv ipython libjpeg-dev memcached libevent-dev libfreetype6-dev zlib1g-dev ffmpeg2theora rabbitmq-server libssl-dev libffi-dev libxml2-dev libxslt1-dev apt-transport-https libjpeg62 libapache2-mod-proxy-uwsgi

Install postgresql 9.3 from https://www.postgresql.org/download/linux/ubuntu/
Install mongodb 3.2 from https://docs.mongodb.com/v3.2/tutorial/install-mongodb-on-ubuntu/
pip2 install markdown

-- Disable installed services:
---------------------------
systemctl disable postgresql.service
systemctl disable postgresql@.service
systemctl disable mongod

And stop those services if running.

mssupdate installserverip gstudio

**Comment by intelliant01** [comment]
@cyberorg MSS shutdown time has increased to over a minute. It could be due to gstudio. Will try to take a shot of the shutdown sequence and report when possible.

**Comment by intelliant01** [comment]
@cyberorg CLIX - Interactives - Clicking on Sugar or Phet is linked to server/sugar and server/phet instead of server/mss/sugar server/mss/phet . Change, if possible.

**Comment by cyberorg** [comment]
shutdown time:
fixed in updated gstudio.

For: CLIX - Interactives 
ln -snf /var/www/html/mss/sugar /var/www/html/
ln -snf /var/www/html/mss/phet /var/www/html/

**Comment by intelliant01** [comment]
@cyberorg Some changes done to code base as well as postgres database on a MSS instance. How to sync it back to the installer? May be I just need to know what all to shutdown before attempting a sync or is there more to it? After sync will create the tar as per the offlineweb instructions.

**Comment by cyberorg** [comment]
systemctl stop gstudio
rsync /home /docker to install server /home/mss/content/gstudiof/home/docker
No tar is used for this

**Comment by intelliant01** [comment]
Have synced back the latest fixes/updates to the install server and tested a manual mssupdate installation with it. Works fine.

Next will assess it closely for performance as at times have felt that it is slower than accessing nroer.gov.in over the internet.
