### ISSUE TITLE
GCompris doesn't start in remote desktop

### ISSUE THREAD

**Issue by geets04** [RechercheTech/mss#53]
GCompris doesn't start using remote desktop . Clicking on `Applications > Education >Educational suite GCompris ` doesn't do anything . When tried to start using `Alt+F2` gives the error as 

>Could not open location 'file:///home/<username>/gcompris'

**Comment by cyberorg** [comment]
none of the games/apps in /usr/games will start in rdp as /usr/games has never been in PATH, use fc for running those apps
