### ISSUE TITLE
factory restore query

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#55]
@cyberorg When restoring from factory restore from boot menu, does it always execute 

```recovery.sh restore 1```

or 

```recovery.sh restore last``` ?

Have a scenario wherein we customise and ship the default device (en and hi) on demand as well as create users if the school requests for it. What are the restore image creation steps we must take to ensure that the factory restore works truly as desired for the customer? Or is it already taken care of?

**Comment by cyberorg** [comment]
snapshot 1 is created as last step done by msssetup, so any customization done after is not covered by that. Modifications done in postmassetup are covered so use that if you need restore point to include any modifications.

**Comment by cyberorg** [comment]
Comment out call to restore_offlineweb_local from restore()

**Comment by intelliant01** [comment]
For installer, should I comment out in /home/mss-images/mss-chroot/usr/bin/recovery.sh so that new installations have it off by default?

To summarize our understanding :
1. All hosted content backup (pre-packaged or user hosted in /var/www/html or /home/*) is not our responsibility to restore.
2. We shall document the pre-packaged content locations and amend documentation to guide the user to manage their own backups.
3. The factory restore process shall not mess with anything in /home or /var/www/html.

Rationale : Not everyone wants the same content.

**Comment by cyberorg** [comment]
New install does not need any additional change. Rest is correct.
