### ISSUE TITLE
Integrate scratch 2.0 offline editor into MSS

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#59]
Replace scratch 1.4 with 2.0.

It is a slightly complicated process but seems worth it -
https://askubuntu.com/questions/913892/how-to-install-scratch-2-on-ubuntu-16-10-or-17-04-64bit/

https://wiki.scratch.mit.edu/wiki/Scratch_Versions#Scratch_2.0

**Comment by cyberorg** [comment]
To get scratch 3.0 web gui
mssupdate ... scratch

To keep it updated see https://github.com/LLK/scratch-gui (git clone, npm run build, use stuff from build folder to create scratch.tar.xz in correct path)

**Comment by intelliant01** [comment]
```
5c5
< tar xf $CONTENT.tar -C /
---
> tar xf $CONTENT.tar.xz -C /
```

**Comment by intelliant01** [comment]
@cyberorg 

> To keep it updated see https://github.com/LLK/scratch-gui (git clone, npm run build, use stuff from build folder to create scratch.tar.xz in correct path)

Failing to build on install server at /home/mssadmin/scratch-gui . Several dependencies were installed manually but it seemed like never ending. Got the hint that npm and node.js may need an update. Then an attempt to update npm fails -

```
#apt-get install npm
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: nodejs but it is not going to be installed
       Depends: node-abbrev (>= 1.0.4) but it is not going to be installed
       Depends: node-ansi (>= 0.3.0-2) but it is not going to be installed
       Depends: node-ansi-color-table but it is not going to be installed
       Depends: node-archy but it is not going to be installed
       Depends: node-block-stream but it is not going to be installed
       Depends: node-fstream (>= 0.1.22) but it is not going to be installed
       Depends: node-fstream-ignore but it is not going to be installed
       Depends: node-github-url-from-git but it is not going to be installed
       Depends: node-glob (>= 3.1.21) but it is not going to be installed
       Depends: node-graceful-fs (>= 2.0.0) but it is not going to be installed
       Depends: node-inherits but it is not going to be installed
       Depends: node-ini (>= 1.1.0) but it is not going to be installed
       Depends: node-lockfile but it is not going to be installed
       Depends: node-lru-cache (>= 2.3.0) but it is not going to be installed
       Depends: node-minimatch (>= 0.2.11) but it is not going to be installed
       Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
       Depends: node-gyp (>= 0.10.9) but it is not going to be installed
       Depends: node-nopt (>= 3.0.1) but it is not going to be installed
       Depends: node-npmlog but it is not going to be installed
       Depends: node-once but it is not going to be installed
       Depends: node-osenv but it is not going to be installed
       Depends: node-read but it is not going to be installed
       Depends: node-read-package-json (>= 1.1.0) but it is not going to be installed
       Depends: node-request (>= 2.25.0) but it is not going to be installed
       Depends: node-retry but it is not going to be installed
       Depends: node-rimraf (>= 2.2.2) but it is not going to be installed
       Depends: node-semver (>= 2.1.0) but it is not going to be installed
       Depends: node-sha but it is not going to be installed
       Depends: node-slide but it is not going to be installed
       Depends: node-tar (>= 0.1.18) but it is not going to be installed
       Depends: node-underscore but it is not going to be installed
       Depends: node-which but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by cyberorg** [comment]
scratch 3 beta now updated

**Comment by intelliant01** [comment]
@cyberorg Using scratch with static mode of MSS i.e. in offline mode requires user to at least once start scratch when having internet connectivity. Subsequent starts in static mode work fine.

![Screenshot at 2019-08-14 12-37-49](https://user-images.githubusercontent.com/2577060/63001240-ca4b2080-be90-11e9-9457-21596a352efb.png)

Tried updating scratch as per above instructions -
> To keep it updated see https://github.com/LLK/scratch-gui (git clone, npm run build, use stuff from build folder to create scratch.tar.xz in correct path)

but am running into this [same problem as earlier](https://github.com/RechercheTech/mss/issues/59#issuecomment-372801691). Do guide what exactly needs to be done to build the new tar on the install server for further testing. Have tried the instructions from https://github.com/LLK/scratch-gui but am unable to get ```npm run build``` to work.

Once updated, shall test and then report in upstream project if the online assets dependency still exists.

**Comment by cyberorg** [comment]
mssupdate $INSTSERVERIP scratch

**Comment by intelliant01** [comment]
![2019-08-15 12 53 45](https://user-images.githubusercontent.com/2577060/63079385-ba354e80-bf2d-11e9-9949-2bfb76ba861e.jpg)
 Tried recreation of the archive but still got the same error. Removed existing archive from /recovery and then only did the update succeed. Next will test in static mode.

**Comment by intelliant01** [comment]
Scratch now loads completely for first time usage even when offline.
