### ISSUE TITLE
Integration with Cybernetyx interactive whiteboard systems

### ISSUE THREAD

**Issue by Harvindersingh0114** [RechercheTech/mss#60]
Install these two packages in the fat client image for integration with interactive whiteboard system from Cybernetyx.

Link to download EyeRIS-IX Driver : 
http://cybernetyx.com/download/eyeris-1.4.74_16B_T2_20170707_CNX_multiarch_online.deb

Link to download IntelliSpace : 
https://cybernetyx.freshdesk.com/support/solutions/articles/23000007103-intellispace-and-resources
https://mega.nz/#!xAImAAza!ZEg--6lidpQM5WcNB_I0jTCN_15WJR59bQKLNucyGME (direct link to deb file)

**Comment by intelliant01** [comment]
@cyberorg This is needed for a very crucial demo. Can we just have a custom FC image for this till we have this as a default? I need to trial these tools prior to the demo.

**Comment by cyberorg** [comment]
For demo install directly on mss as before, will create custom client image once we have orders.

**Comment by intelliant01** [comment]
@cyberorg If we do not connect the MSS directly to the cybernetyx infra and use it only as a fat-client image server then I guess we do not need to do this - "install the packages directly on MSS(apt update && apt install /path/to/packages.deb" or do we?

**Comment by intelliant01** [comment]
@cyberorg Is there a way we can ensure that only designated machines (MAC id basis) use this image for booting?
That way a school using the MSS for around 8 smart classrooms and 30 lab computers will not have to use this image for the lab clients.

**Comment by cyberorg** [comment]
yes, do it same way we provide i386 image for unsupported clients, see ls /etc/nbd-server/conf.d/ for example of serving multiple images and add menu entry to /var/lib/tftpboot/ltsp/amd64/pxelinux.cfg/01-08-00-27-d1-61-9f for example, the last part is mac address of clients needing special image
