### ISSUE TITLE
Include Openboard in the standard image instead of Pylote

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#62]
Include [Openboard ](https://github.com/OpenBoard-org/OpenBoard/releases/) in the standard image instead of Pylote done earlier in #46 as it is a much more mature and well documented product.

**Comment by cyberorg** [comment]
Not interested at the moment, reopen when significant number of customers requests it.

**Comment by intelliant01** [comment]
Openboard integrated in 16.04. 
For 18.04 openboard package not yet available. Instead Pylote v2 and Kazam have been integrated.


> [11:04 AM, 2/22/2019] Jigish Gohil: https://github.com/OpenBoard-org/OpenBoard/issues/177#issuecomment-452649433
[4:20 PM, 2/22/2019] Jigish Gohil: Update 18.04 image, try pylote and kazan
[4:20 PM, 2/22/2019] Jigish Gohil: http://pascal.peter.free.fr/pylote-en.html
