### ISSUE TITLE
Incorporate Brio interactive whiteboard software in the client image

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#63]
@cyberorg The Brio interactive board software is available herein - 
https://drive.google.com/file/d/1oIMaH0wlhayU7Q-9LNh72Q8Rz658JJba/view?usp=drivesdk

**Comment by cyberorg** [comment]
On install server /home/mss/brio.img, replace default image on the client with that one

**Comment by geets04** [comment]
@cyberorg Getting this error.

![screenshot at 2018-05-29 11-31-30](https://user-images.githubusercontent.com/15116955/40640499-eac9111e-6333-11e8-8259-5f8bd6cfcebd.png)
