### ISSUE TITLE
Zabbix monitoring on new installation not working

### ISSUE THREAD

**Issue by geets04** [RechercheTech/mss#67]
Adding newly installed device on zabbix doesn't shows the monitoring graph. Shows the below error : 

`root@server:~# systemctl status zabbix-proxy.service `
`● zabbix-proxy.service - Zabbix Proxy Loaded: loaded (/lib/systemd/system/zabbix-proxy.service; enabled; vendor preset: enabled) Active: activating (auto-restart) (Result: resources) since Fri 2018-08-03 12:17:07 IST; 4s ago Process: 4621 ExecStop=/bin/kill -SIGTERM $MAINPID (code=exited, status=0/SUCCESS) Process: 4757 ExecStart=/usr/sbin/zabbix_proxy -c $CONFFILE (code=exited, status=0/SUCCESS)  Main PID: 4618 (code=exited, status=1/FAILURE)`
`root@server:~# /etc/init.d/zabbix-proxy restart `
`[....] Restarting zabbix-proxy (via systemctl): zabbix-proxy.serviceJob for zabbix-proxy.service failed because a configured resource limit was exceeded. See "systemctl status zabbix-proxy.service" and "journalctl -xe" for details.  failed! `

**Comment by cyberorg** [comment]
Try 
rm /var/lib/zabbix/zabbix_proxy.db* && /etc/init.d/zabbix-proxy restart

**Comment by geets04** [comment]
On trying rm /var/lib/zabbix/zabbix_proxy.db* && /etc/init.d/zabbix-proxy restart gives the following error: 

`mssadmin@server:~$ systemctl status zabbix-proxy.service`
`● zabbix-proxy.service - Zabbix Proxy
   Loaded: loaded (/lib/systemd/system/zabbix-proxy.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: resources) since Tue 2018-08-07 10:54:09 IST; 786ms ago
  Process: 4791 ExecStop=/bin/kill -SIGTERM $MAINPID (code=exited, status=0/SUCCESS)
  Process: 4812 ExecStart=/usr/sbin/zabbix_proxy -c $CONFFILE (code=exited, status=0/SUCCESS)
 Main PID: 4790 (code=exited, status=1/FAILURE)`

`Aug 07 10:54:09 server systemd[1]: Failed to start Zabbix Proxy.
Aug 07 10:54:09 server systemd[1]: zabbix-proxy.service: Unit entered failed state.
Aug 07 10:54:09 server systemd[1]: zabbix-proxy.service: Failed with result 'resources'.`

**Comment by geets04** [comment]
Solved,
Steps : 
1) `sudo su -`
2) `rm /var/lib/zabbix/zabbix_proxy.db* && /etc/init.d/zabbix-proxy restart`
