### ISSUE TITLE
Boot menu not visible in atleast last 3 months installation

### ISSUE THREAD

**Issue by geets04** [RechercheTech/mss#68]
Fixed the problem by doing the below steps -

![2882](https://user-images.githubusercontent.com/15116955/43903769-c4b16a20-9c0a-11e8-98ea-f1434583bc42.jpg)

sudo gedit /etc/default/grub 

commenting 
#GRUB_DEFAULT=0
#GRUB_HIDDEN_TIMEOUT=0
#GRUB_HIDDEN_TIMEOUT_QUIET=true
#GRUB_TIMEOUT=10
#GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`

and adding
GRUB_DISTRIBUTOR="My sCool Server" 

then
update-grub 

---

@cyberorg Do check why this is happening when everything else is fine on new installations.

**Comment by cyberorg** [comment]
enabling updates during install has messed with installed script. To fix the devices already  installed

cp /usr/sbin/update-grub.backup /usr/sbin/update-grub
update-grub
