### ISSUE TITLE
Integrate Freeplane

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#70]
Freeplane seems a much more mature tool for teaching mindmap concepts compared to VYM, as per user experiences. Hence add Freeplane.

**Comment by cyberorg** [comment]
apt remove vym
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  vym
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 7,502 kB disk space will be freed.

apt install freeplane
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  ant ant-optional groovy ivy jmapviewer libcommons-cli-java libcommons-codec-java libcommons-lang-java libgpars-groovy-java
  libhawtjni-runtime-java libidw-java libjansi-java libjansi-native-java libjcommander-java libjcsp-java libjgoodies-forms-java libjline2-java
  libjsr166y-java libjsyntaxpane-java libknopflerfish-osgi-framework-java libmnemonicsetter-java libmultiverse-core-java libnetty-3.9-java
  libqdox-java libsvgsalamander-java libxpp3-java libxstream-java simplyhtml
Suggested packages:
  ant-doc javacc jython libactivation-java libbcel-java libcommons-net-java libmail-java libjdepend-java libjsch-java liboro-java libxz-java
  freeplane-scripting-api groovy-doc libjsch-agent-proxy-java libbcprov-java libbcpg-java ivy-doc libcommons-lang-java-doc
  libgpars-groovy-java-doc libjcommander-java-doc libjcsp-java-doc libjgoodies-forms-java-doc libbcpkix-java libjboss-logging-java
  libnetty-tcnative-java libprotobuf-java libslf4j-java libqdox-java-doc libcglib-nodep-java libdom4j-java libjdom2-java libjettison-java
  libjoda-time-java libkxml2-java libwoodstox-java simplyhtml-doc
The following NEW packages will be installed:
  ant ant-optional freeplane groovy ivy jmapviewer libcommons-cli-java libcommons-codec-java libcommons-lang-java libgpars-groovy-java
  libhawtjni-runtime-java libidw-java libjansi-java libjansi-native-java libjcommander-java libjcsp-java libjgoodies-forms-java libjline2-java
  libjsr166y-java libjsyntaxpane-java libknopflerfish-osgi-framework-java libmnemonicsetter-java libmultiverse-core-java libnetty-3.9-java
  libqdox-java libsvgsalamander-java libxpp3-java libxstream-java simplyhtml
0 upgraded, 29 newly installed, 0 to remove and 0 not upgraded.
Need to get 43.3 MB of archives.
After this operation, 159 MB of additional disk space will be used.

Hence no Freeplane

**Comment by intelliant01** [comment]
@cyberorg Will revert with packages that can be removed from image that are not being used anywhere in our knowledge as yet.

**Comment by intelliant01** [comment]
@cyberorg Kicad may be removed. 
[Herein is](https://docs.google.com/document/d/1crfKmk1rqq2YlF_V6TJGNd42R8FiJH9Yy006C5ZHv0M/edit?usp=sharing) what we had evaluated in various curriculum's and books popular around the country for K-12.
Those specific to higher education can be removed.
If you can provide a list of large software packages then it will help to quickly zero upon the redundant ones which will be most effective to remove.

**Comment by intelliant01** [comment]
@cyberorg Scilab also not needed for K-12.

**Comment by cyberorg** [comment]
added in updated images
