### ISSUE TITLE
Upgrade Gcompris

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#71]
There are a lot of new activities in upgraded Gcompris.  These are useful for preschool prospects which our new dealers are also approaching.

**Comment by intelliant01** [comment]
This may only be possible on 18.04 LTS now as the project seems to have moved to gcompris-qt i.e. a qt based rewrite. No release available on 16.04.

**Comment by cyberorg** [comment]
added to 1804

**Comment by intelliant01** [comment]
Rare use case. But since it is part of MSS, it should have worked.

Doesn't work over FreeRDP + XVNC connection -

![mstsc_xfsjqmotso](https://user-images.githubusercontent.com/2577060/52727661-b6a32800-2fdb-11e9-833d-fa126656b2ca.png)

**Comment by cyberorg** [comment]
https://bugreports.qt.io/browse/QTBUG-66935

**Comment by intelliant01** [comment]
@cyberorg So I think we should enable the required extension as we have control over our environment. Not sure by when the patch will make its way through or would you suggest waiting?

**Comment by cyberorg** [comment]
There is nothing we can fix, even with new qt 511 gcompris-qt fails elsewhere, report it to gcompris(https://bugs.kde.org/buglist.cgi?quicksearch=gcompris) if you think there are people wanting to run gcompris over xrdp.

Following suggestion on https://gcompris.net/index-en.html does not work, 

"On Linux and Windows, we used to have two separate installers for OpenGL and software rendering. Now both rendering modes are available from the same installer. By default we try to use the OpenGL rendering, and if not working, we show an error and switch to the software rendering. This automatic switch is new and may not work everywhere. In case it doesn't, you can manually select the software rendering mode by editing the configuration file (in ~/.config/gcompris/gcompris-qt.conf for Linux, %LocalAppData%/gcompris/GCompris.conf for Windows): find the line "renderer=auto", replace auto with software and save the file. We are also interested to get some feedback to help us improve this auto-detection. "

LIBGL_ALWAYS_SOFTWARE=1 gcompris-qt does not work either.

**Comment by intelliant01** [comment]
Won't attempt a fix unless there is a solid use-case.
