### ISSUE TITLE
Integrate software usage tracking thyme

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#72]
Granular software usage tracking shall be helpful for some of our clients. [Sourcegraph's Thyme](https://github.com/sourcegraph/thyme) may help achieve this. Its integration needs to be explored.

**Comment by cyberorg** [comment]
Use zabbix for monitoring processes, add the template all the app that need tracking.

Have added zabbix-agent to client image. Need another zabbix server, prime.cyberorg.co.in will not be available.

**Comment by intelliant01** [comment]
To where will the zabbix-agent publish to as of now? 
We don't need this yet in the standard image. It is only needed when we have a large scale deployment confirmed, hence in a custom image only. And that is when we shall deploy a specific zabbix monitoring server.
As already conveyed earlier, by March end we shall decide about moving from prime.cyberorg.in for all purposes.

**Comment by intelliant01** [comment]
> Point analytics.myscoolserver.com to 1.22.160.51

Done

So wherever we deploy hereafter, we shall have the userlevel app usage stats as and when they have internet on their network?

**Comment by cyberorg** [comment]
modify all current installations /etc/zabbix/zabbix_proxy.conf 
Server=analytics.myscoolserver.com

all new installs will have this.

**Comment by cyberorg** [comment]
In theory on new 1804 install, modifying  mss server /var/lib/tftpboot/ltsp/amd64/lts.conf 
RCFILE_03="systemctl start zabbix-agent"

should start zabbix-agent on all clients.

**Comment by intelliant01** [comment]
Explore https://graphiteapp.org/ because zabbix still may not get us user level granular reports.

**Comment by intelliant01** [comment]
@cyberorg Looks like this can be used OOTB both for application usage data collection and consolidated representation at least in the isolated lab context -
https://github.com/cilcoberlin/panoptes 
http://languages.oberlin.edu/projects/panoptes-usage-tracker/ - has a screenshot

thyme serves the broad need of offline collection and online syncing for the large scale projects while panoptes can serve the isolated private school needs without having to do any development.

**Comment by cyberorg** [comment]
Dead project made for mac and windows clients

**Comment by cyberorg** [comment]
As far as my involvement in this is concerned, zabbix and thyme are both integrated in client image.

**Comment by cyberorg** [comment]
https://nicolargo.github.io/glances/ lists processes also, we can probably get user information with running processes.
https://github.com/selfspy/selfspy/network lot of active forks

**Comment by intelliant01** [comment]
21/2/19 - cyberorg: https://github.com/cyberorg/thymetrack is now part of 1804 image . Details therein.

**Comment by intelliant01** [comment]
Has been refined by @cyberorg to ensure that reports for each user are generated during proper shutdown or when server is started next instead of every hour.

Known limitation: Though the reports are available offline but viewing them requires access to an online js library, hence the system on which we are trying to view the reports in a browser should have internet connection.

So this brings us to a minimum viable feature. Next we may work towards a central viewing console.

**Comment by intelliant01** [comment]
Added `home.mount` to `Requires`, `After`, `BindsTo` in `/lib/systemd/system/thymereport.service` to enforce the dependency of thyme report service on `/home` partition being mounted.
