### ISSUE TITLE
Integrate Sigil 

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#74]
Very useful tool for teachers. Have evaluated several EPUB editing tools and then zeroed upon this. Also NCERT has trained all the SRG teams in usage of this.
https://sigil-ebook.com/

No official package available as yet, only through PPA - http://ubuntuhandbook.org/index.php/2018/07/sigil-0-9-10-released-install-ubuntu-18-04/

At the time of taking this up, we need to at least reconsider Calibre as well.

**Comment by cyberorg** [comment]
0.9.9 is in official 18.04 repo, adding that.

No new app/feature will be added to 1604.
