### ISSUE TITLE
Support multiple images e.g. cybernetyx along with other client images

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#78]
Some legacy software are not yet available for 18.04 but the same are critical for usage in some schools. To address this scenario, we need to give an option to boot into old 16.04 image.

**Comment by cyberorg** [comment]
1. Create /etc/nbd-server/conf.d/ltsp-cyb.conf with this

[/opt/ltsp/cyb]                                                                   
exportname = /opt/ltsp/images/cyb.img
readonly = true                                                                       
authfile = /etc/ltsp/nbd-server.allow

2. wget http://serverip/mss/.ltsp-cybernetyx -O /opt/ltsp/images/cyb.img

3. Add to /var/lib/tftpboot/ltsp/amd64/pxelinux.cfg/default

label Cybernetyx
kernel linux-cyb
append ro initrd=initrd-cyb init=/sbin/init-ltsp forcepae root=/dev/nbd0 nbdroot=/opt/ltsp/cyb quiet splash vt.handoff=7 ltsp.REMOTE_APPS=true ltsp.LDM_LANGUAGE=en_IN.UTF-8
ipappend 3

4. 
mkdir tmount
mount /opt/ltsp/images/cyb.img tmount
cd tmount/boot/
cp initrd*-generic /var/lib/tftpboot/ltsp/amd64/initrd-cyb
cp vmlinuz*-generic /var/lib/tftpboot/ltsp/amd64/linux-cyb                      
chmod +r /var/lib/tftpboot/ltsp/amd64/*
cd -                                                                                 
umount tmount                                                                      
rmdir tmount

**Comment by intelliant01** [comment]
@geets04  Use
```mssupdate <serverip> smart1604``` for en + hi 
or 
```mssupdate <serverip> smart1604gu``` for en + hi + gu with gu as default.

**Comment by intelliant01** [comment]
For all valid update paths refer ```postmsssetup```.
