### ISSUE TITLE
Client screen control via Android handlhelds or graphics tablet

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#79]
Screen control enabled with -

1. xmouse - tested 
  - Add to ```lts.conf```
    - ```RCFILE_0x=/usr/sbin/sshd``` for 1604 
    - ```RCFILE_0x=systemctl start ssh``` for 1804

For xmouse app change display port to :7.

2. wacom like bluetooth graphics tablet need to be tested. Should work out of the box (https://linuxwacom.github.io/).

**Comment by intelliant01** [comment]
> wacom like bluetooth graphics tablet need to be tested. Should work out of the box (https://linuxwacom.github.io/).

CTL410WL works like a charm.

**Comment by cyberorg** [comment]
https://play.google.com/store/apps/details?id=io.appground.blek

Alternative to x mouse, this uses Bluetooth, works as normal BT keyboard and touchpad mouse with any device

After pairing device, HID option show up, go to app on android phone and select "USE THIS DEVICE"

![bt-hid-setup](https://user-images.githubusercontent.com/1300602/67079337-a10c8080-f1b0-11e9-9e1f-2df11df6224e.png)
![bt-input](https://user-images.githubusercontent.com/1300602/67079346-a669cb00-f1b0-11e9-8e14-4aab677f0bb8.png)

**Comment by intelliant01** [comment]
The HID option did not show for me over multiple attempts. Will try again and revert.

**Comment by intelliant01** [comment]
Not working for me.

**Comment by intelliant01** [comment]
Pairing of Wacom tablet is not persisted across reboots of client (tested with NUC and laptop as client). 

During boot and prior to login screen this is always visible - 

![IMG_20200115_131023__01](https://user-images.githubusercontent.com/2577060/72416366-82f8f100-379c-11ea-8800-e5f1ad617c0d.jpg)

The last 4 connections always show up but greyed out -

![IMG_20200115_153329__01](https://user-images.githubusercontent.com/2577060/72425763-682f7800-37ae-11ea-8421-7bf83efacd67.jpg)

The version of bluez is same as that on server but persistence works on server -

![IMG_20200115_131838__01](https://user-images.githubusercontent.com/2577060/72416373-87bda500-379c-11ea-9135-9fe3cdb13724.jpg)

Output of ```hciconfig -a``` from client -

![IMG_20200115_154629__01](https://user-images.githubusercontent.com/2577060/72425793-72ea0d00-37ae-11ea-9301-5c78f98b389b.jpg)

Output of ```hciconfig -a``` from server -

![IMG_20200115_155041__01](https://user-images.githubusercontent.com/2577060/72426015-f0ae1880-37ae-11ea-8007-c16dc8a616d0.jpg)

Difference being the 'PSCAN' status.
Looks like the discoverability is not being turned on in the client.
https://unix.stackexchange.com/questions/92036/enabling-bluetooth-discoverability-upon-start-up

Tried adding to `lts.conf` to no avail -

```
RCFILE_05="hciconfig hci0 piscan"
```
Result -
![IMG_20200115_164401__01](https://user-images.githubusercontent.com/2577060/72430320-0d028300-37b8-11ea-9ee7-521e266c0c4c.jpg)

```
RCFILE_04="hciconfig hci0 up"
RCFILE_05="hciconfig hci0 piscan"
```
Result -
![IMG_20200115_165454__01](https://user-images.githubusercontent.com/2577060/72430319-0c69ec80-37b8-11ea-9a97-8562cce6b992.jpg)

**Comment by cyberorg** [comment]
On MSS
echo '/var/lib/bluetooth/       *(rw,no_root_squash,async,no_subtree_check)' >> /etc/exports

Add the following in /var/lib/tftpboot/ltsp/amd64/lts.conf
RCFILE_03="mount server:/var/lib/bluetooth /var/lib/bluetooth"

Recent bluetooth connections can be connected without re-pairing
