### ISSUE TITLE
Update Li-f-e iso to 18.04 for 1804 installations

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#81]
This will also enable those who are using 1804 to install almost identical dekstop env with applications in their personal workspaces at home even if the ISO does not provide the exact same set of software.

It is okay if we have to remove the installer support from the boot menu.

**Comment by cyberorg** [comment]
switchmss.sh will now handle this.

It is not removed from the boot menu, it should work as 1604 does.

Add to FAQ: 
Why Li-f-e.iso is not identical to MSS?
Some of the applications are left out from Li-f-e with learning in mind, students can get familiar with how the applications are installed on GNU/Linux distributions by doing it themselves, they can explore wonderful world of free software and try out many more useful applications not installed by default.
