### ISSUE TITLE
Dzongkha support needed in LTSP images

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#82]
Dzongkha support needed in LTSP images - lab and smart class images.

**Comment by cyberorg** [comment]
https://www.transifex.com/mate/MATE/

Just 36%, will add whatever is the current status provided by the distribution.

**Comment by cyberorg** [comment]
/home/mss/.ltsp-1804-btw now has dz

To configure during msssetup use the following for included languages

gu_IN
hi_IN
dz_BT

**Comment by intelliant01** [comment]
> gu_IN
> hi_IN
> dz_BT

as_IN also supported as before?

**Comment by cyberorg** [comment]
Nothing is removed, test to see if all incorporated languages work.
