### ISSUE TITLE
ntp server not working in static mode

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#87]
When MSS is in static mode, the client devices fail to update their time from the server.

Herein are attached the working configuration of dynamic mode and the non-working one of static mode.

[dynamic.ntp.conf.txt](https://github.com/RechercheTech/mss/files/3500046/dynamic.ntp.conf.txt)
[static.ntp.conf.txt](https://github.com/RechercheTech/mss/files/3500045/static.ntp.conf.txt)

Related to #41

**Comment by cyberorg** [comment]
mssupdate $INSTSERVERIP ntpfix

leave the issue open

**Comment by intelliant01** [comment]
Small typo in ntpfix script wherein xz needed to be appended to the archive name.

Now works fine both for static and dynamic mode of MSS.
