### ISSUE TITLE
provide openboard based on boot menu selection.

### ISSUE THREAD

**Issue by cyberorg** [RechercheTech/mss#89]
With 1804 only single image will be maintained as keeping multiple images is not possible.

Devise a way to provide openboard based on bootmenu entry.

Add ltsp.SMARTCLASS=true to boot menu options.

Example:

label Smartboard
kernel vmlinuz
append ro initrd=initrd.img init=/sbin/init-ltsp forcepae root=/dev/nfs nfsroot=/opt/ltsp/images ltsploop=amd64.img quiet splash vt.handoff=7 ltsp.REMOTE_APPS=true ltsp.LDM_LANGUAGE=en_US.UTF-8 ltsp.SMARTCLASS=true video=LVDS-1:d video=eDP-1:d
ipappend 3

Feature available in 18043 image.

See also issue #88

**Comment by cyberorg** [comment]
Create sbmenu post script that replaces #SMARTCLASS tag in pxelinux.cfg/default with the example above.

**Comment by intelliant01** [comment]
Modified `ltspsmart1804up` and also `enablessh` for Android based screen control.
