### ISSUE TITLE
Integrate Kolibri 0.13 and kolibri-server into the 180403 MSS release

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#92]
Refer ```kolibri-server``` installation script on install server and integrate the requisite packages for getting kolibri-server and kolibri 0.13 to be installed by default on 180403. 

I think we can apply this deep integration as Kolibri is going to remain a core part of MSS.
This is needed because as of now too many queries need to be answered during the manual install process.
Note: Answer to one question - **Do you wish to run Kolibri on startup?** will be **No** during the ```apt install kolibri-server``` because ```kolibri-server``` is in turn responsible for starting `kolibri`.

The content will still be loaded dynamically at post-msssetup stage via ```kolibricontent```.

**Comment by cyberorg** [comment]
kolibri packages are preinstalled now.

**Comment by cyberorg** [comment]
discovered issue with kolibri-server on mss, still using port not uwsgi socket
