### ISSUE TITLE
Onscreen keyboard for client login screen

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#94]
In a smartclass scenario wherein the tablet connects to the teacher's system upon boot, the only need for a keyboard seems to be for login purpose. 
Hence having an onscreen keyboard option during login is going to be great for user experience as well as slightly cost effective.

**Comment by cyberorg** [comment]
Onboard does not work as expected on ldm screen.

**Comment by cyberorg** [comment]
This will be possible only in new LTSP, nothing can be done now.

**Comment by intelliant01** [comment]
Works in latest images as they support the "new LTSP" .
