### ISSUE TITLE
Update Kolibri to 0.13.1 in the default installation

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss#95]
Kolibri 0.13.1 has been released with some major bug fixes. Integrate it in the installer. 
Am currently updating it via post.

**Comment by cyberorg** [comment]
If the bug fixes are not in the packages then best you update /usr/bin/kolibri using pex in post as installing/updating kolibri package in install image is lot more complicated.

**Comment by intelliant01** [comment]
Bug fixes are in the packages. Shall update to the latest packages via post and hopefully will be able to do so without any interactive dialogues that shall stem the process. Shall update herein after trying tomorrow.

**Comment by intelliant01** [comment]
Tried with this but still have to manually handle a prompt for okaying manual start of Kolibri -
```
apt-get install -y software-properties-common
add-apt-repository -y ppa:learningequality/kolibri
apt-get update
apt-get install kolibri
```

**Comment by intelliant01** [comment]
Have done via apt-add..., apt update, apt get in a postmsssetup script but there is a needless interactive `ok` prompt that can't be handled by any apt flag. Will try to propose to project to simply include that information in post-inst on the terminal rather than a prompt.

This only seems the best way for now as Kolibri will keep evolving all the time.

**Comment by cyberorg** [comment]
18044 has 0.31.1

packaging(install and post install scripts) does not evolve, just replacing /usr/bin/kolibri with kolibri.pex should be sufficient.

**Comment by intelliant01** [comment]
Something is different in the way Kolibri works with only .pex, only .deb and kolibri-server + kolibri. Several cases are there in the forum as well as github wherein this had to be taken care of. Additionally reporting error scenarios and reproducing them becomes that much more complex. Will live with the current mssupdate method to get the latest.
